version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: creditsys
    ports:
      - "5432:5432"
#  liquibase:
#    image: liquibase/liquibase
  bank_answer:
    container_name: bank_answer
    build: ./bank_answer
    restart: always
    ports:
      - "8086:8086"
    command: java -jar ./app/bank_answer.jar
#  credit_system:
#    build: ./credit_system
#    restart: always
#    ports:
#      - "8080:8080"
#    command: java -jar ./app/credit_system.jar
