server:
  port: 8086
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: kafka:9092, localhost:9092
      group-id: app.1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka:9092, localhost:9092,
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mvc:
    servlet:
      path: /bank_answer
