
FROM alpine/git AS git

WORKDIR /usr/src/
RUN git clone https://github.com/yourihdx/sber-jd-course-project.git

FROM maven:3.8.1-openjdk-8 AS maven-build

WORKDIR /usr/src
COPY --from=git /usr/src/sber-jd-course-project/bank_answer ./bank_answer
COPY --from=git /usr/src/sber-jd-course-project/pom.xml ./pom.xml
#COPY /sber-jd-course-project/bank_answer ./bank_answer
#COPY /sber-jd-course-project/pom.xml ./pom.xml

WORKDIR /usr/src/bank_answer
RUN mvn dependency:go-offline
RUN mvn package spring-boot:repackage 
#-DskipTests


FROM openjdk:8-jre

ENV TZ=Europe/Moscow

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 8086

RUN mkdir /app

WORKDIR /app

COPY --from=maven-build /usr/src/bank_answer/target/bank_answer.jar ./app/bank_answer.jar
