version: '2'
services:
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: creditsys
    ports:
      - "5432:5432"
