FROM alpine/git AS git
WORKDIR /usr/src/

RUN git clone https://github.com/yourihdx/sber-jd-course-project.git

FROM maven:3.8.1-openjdk-8 AS maven-build-sch

WORKDIR /usr/src
COPY --from=git /usr/src/sber-jd-course-project/schedule ./schedule
COPY --from=git /usr/src/sber-jd-course-project/pom.xml ./pom.xml
WORKDIR /usr/src/schedule
RUN mvn package spring-boot:repackage
FROM openjdk:8-jre

EXPOSE 8087

RUN mkdir /app

WORKDIR /app

COPY --from=maven-build-sch /usr/src/schedule/target/schedule-0.0.1-SNAPSHOT.jar ./app/schedule.jar

